### ISSUE TITLE
udp.cc中对接收数据的处理出现异常

### ISSUE THREAD

**Issue by virqin** [yedf/handy#10]
```
        int fd = channel_->fd();
        ssize_t rn = recvfrom(fd, buf.makeRoom(kUdpPacketSize), buf.space(), 0, (sockaddr*)&raddr, &rsz);
        if (rn < 0) {
            error("udp %d recv failed: %d %s", fd, errno, strerror(errno));
            return;
        }
        buf.addSize(rn); //测试到有时recvfrom返回为0，即rn=0，addSize就会把buf内存搞砸
        trace("udp %d recv %ld bytes from %s", fd, rn, Ip4Addr(raddr).toString().data());
        this->msgcb_(shared_from_this(), buf, raddr);
```
释放内存错误`*** Error in `./udp-cli': double free or corruption (top): 0x0000000000f555e0 ***`

顺带问一下，什么情况下recvfrom返回0? 设定了非阻塞模式？我抓包看一下发送端

**Comment by yedf** [comment]
看了相关的代码，并没有发现buf.addSize在处理rn=0的逻辑有问题。你能否提供重现问题的例子呢？

**Comment by virqin** [comment]
@yedf  昨晚找了一下出问题的情况，我这边使用udp-svr/udp-cli进行测试收发，问题在于下面makeRoom和space执行的顺序：
`ssize_t rn = recvfrom(fd, buf.makeRoom(kUdpPacketSize), buf.space(), 0, (sockaddr*)&raddr, &rsz);`
这样没有问题：
```
char *pbuf = buf.makeRoom(kUdpPacketSize);
ssize_t rn = recvfrom(fd, pbuf, buf.space(), 0, (sockaddr*)&raddr, &rsz);
```
深究的话似乎是参数压栈顺序从右向左，而space方法依赖makeRoom，就是先调用space的话返回0

延伸：你那边没有问题吗？并且UDP允许发送0字节的数据，rn=0的话就会出现释放内存错误`*** Error in./udp-cli': double free or corruption (top): 0x0000000000f555e0 ***`

使用库的makefile编译的：
```
debian:~$ gcc --version
gcc (Debian 4.9.2-10) 4.9.2
```

**Comment by yedf** [comment]
上述代码直接调用space是有问题的，已经修复为

**Comment by virqin** [comment]
:+1:
