### ISSUE TITLE
与muduo库的比较的几个小疑问

### ISSUE THREAD

**Issue by liketemple** [yedf/handy#14]
楼主声明handy是受muduo库启发而写。恰巧不是特别习惯依赖boost的库，因此首选handy，非常欣赏handy的清爽简洁。在与muduo进行比较后有一些小疑问，其中最困惑的是：
为什么没有类似muduo库中 sendinloop 这样的设计？
在eventBase的设计中，有线程池，那很有可能库使用者会使用线程池完成耗时任务（同时将connection传递给工作线程），在任务结束时使用connection发送结果数据。muduo的设计中有 sendinloop 保证关于socket的读写都在同一个loop线程中，不知道为什么handy中没有这样的设计，是有什么特殊考虑吗？
看到设计中有 safeCall，为什么没有 safeSend 这样的设计？😆

**Comment by qq66921494** [comment]
TcpConnPtr->getBase()->safeCall([]{
    // TODO::::这里就可以safeSend了
});

**Comment by choleraehyq** [comment]
muduo有一个cpp11的分支，里面基本把boost的部分都用c++11的对应特性替换掉了。

**Comment by yedf** [comment]
muduo的cpp11分支的风格还是偏向于boost的，自己更喜欢lamda而不是bind，因此也会觉得handy更简洁顺手一些
