### ISSUE TITLE
为何safequeue要继承std::mutex?

### ISSUE THREAD

**Issue by DeathPoem** [yedf/handy#20]
template<typename T> struct SafeQueue: private std::mutex, private noncopyable,在threadpool.h 14 行。 完全不懂？为何不直接添加一个mutex成员呢？

**Comment by yedf** [comment]
可以添加mutex成员，使用继承省去了命名，能够直接把自己当做锁对象，更加简洁

**Comment by DeathPoem** [comment]
谢谢。
