### ISSUE TITLE
检测系统的预定义宏的问题

### ISSUE THREAD

**Issue by yanxijian** [yedf/handy#21]
目录代码里面用的是 OS_LINUX 和 OS_MACOSX，我从 [StackOverflow ](https://stackoverflow.com/questions/5919996/how-to-detect-reliably-mac-os-x-ios-linux-windows-in-c-preprocessor)上看到的和[这里](https://sourceforge.net/p/predef/wiki/OperatingSystems/)看到的，分别用 \_\_linux\_\_ 和 \_\_APPLE\_\_ 会不会更好一些呢？
上面问题是我在编译 hany 时，在 handy\poller.cc  和 handy\port_posix.cc 中遇到的。

**Comment by yedf** [comment]
项目里面有个build_config脚本，他会检测操作心痛，并在编译的时候传递OS_LINUX，所以原来的写法也是没有问题的

**Comment by yanxijian** [comment]
哈哈，这个确实没注意，当时拿Visual Studio远程编译的。谢谢解答
