### ISSUE TITLE
单机并发千万，个人觉得"并发"一词用法不当。

### ISSUE THREAD

**Issue by y123456yz** [yedf/handy#29]
单机并发千万，个人觉得"并发"一词用法不当，千万这个我猜对应的应该是多网卡物理机的qps，这个不叫并发。

要真并发千万，你一台物理机瞬间就给你压挂了。

你的千万应该指的是QPS吧，而且是长连接的qps(长链接估计也到不了，网卡队列软中断会消耗大量CPU)，短连接qps更不可能到千万。
每个连接都要耗几十K内存，千万qps你内存也早爆了，CPU也抗不住的。

京东这种电商双11规模估计也才千万并发，并发的意思楼主可能误解了。

**Comment by restmad** [comment]
可能说的是长连接吧

**Comment by yedf** [comment]
qps指的是query per seconds，是每秒请求数量。
单机千万并发连接我指的是同时保持千万个长连接。
千万条连接，每条连接约4K的内存，总共下来大约40G，内存没有爆，使用的是epoll模型，CPU也不会爆，而且还不高。
我的文章里面有提到qps大约是几万，在极光推送这类的应用中，就会出现这类的场景，连接很多，但qps很少，此时一台机器可以扛住大量大量的连接

**Comment by y123456yz** [comment]
并发的意思不是同时保持的链接，并发的意思是客户端同时发起链接。

内核协议栈会给每个链接分配一个读buf和写buf空间，有几个阈值，如果千万链接同事有数据首发，你内存早爆了，除非你每个链接完全是空链接，不发送数据。

你找多台客户端压一下，客户端开一千万个线程同时发起链接试试。客户端大量报错，服务端根本就处理不过来。

多进程模型同时accept客户端链接(nginx网络模型)，linux-3.9一下内核版本不支持Reuseport ,多线程条件下内核无法做到链接负载均衡，accept线程收到这个限制，单机并发也就十万级别。如果内核版本大于3.9，内核负载自动实现accept分发到不同的accept应用线程，这种情况下并发也不会超过百万级。

如果应用程序是一个accept线程接收链接，然后分发到各个工作线程读写数据(memcached模型)，并发会更低，因为同一时刻只会有一个线程处理客户端accept事件信息。

**Comment by restmad** [comment]
个人理解，并发应该是同一时刻

**Comment by wardenlym** [comment]
保持千万个长连接  确实不等于 千万并发

保持长连接所需要的消耗并不高，如果没请求，调高内核参数，所耗费的只有内存而已。
能有几万的并发，已经是很高性能的服务器了。

**Comment by skyformat99** [comment]
各位大佬，写个压测程序试试看啊。
不知道效果如何呢？     长连接，同时发送ping-pong数据才算 。单连接不算。

**Comment by yedf** [comment]
其实我的这篇文章里面写得很清晰，并发的连接有千万，里面有详细的步骤
https://zhuanlan.zhihu.com/p/21378825
对于前面提出来的同时创建连接，实际应用不会大量大量的用户同时上线或退出的，可以看成是一段时间内上线退出，这就不存在楼上的情况了

**Comment by y123456yz** [comment]
你那个应该叫总的链接数，不应该叫并发的链接。
会有歧义，容易误导。
例如我前两天无意中看到你这个，第一感觉：这个项目可以支持单机千万并发。

**Comment by gaigeshen** [comment]
说的是千万同时在线吧
