### ISSUE TITLE
 Mac OS X 10.11 编译EchoDemo失败

### ISSUE THREAD

**Issue by vincent-coding** [yedf/handy#3]
mabook:~ vincent$ cat main.cpp
#include <handy/handy.h>

using namespace std;
using namespace handy;

int main(int argc, const char* argv[]) {
    EventBase base;
	//handle ctrl+c
	Signal::signal(SIGINT, [&]{ base.exit(); }); 
	TcpServer echo(&base);
	int r = echo.bind("", 99);
	exitif(r, "bind failed %d %s", errno, strerror(errno));
	echo.onConnRead([](const TcpConnPtr& con) {
				   con->send(con->getInput());
				 });
	 base.loop(); 
	 //enter events loop
}
mabook:~ vincent$ clang main.cpp -o server -std=c++11
In file included from main.cpp:1:
In file included from /usr/local/include/handy/handy.h:4:
In file included from /usr/local/include/handy/http.h:4:
In file included from /usr/local/include/handy/conn.h:2:
In file included from /usr/local/include/handy/event_base.h:3:
/usr/local/include/handy/poller.h:14:2: error: "platform unsupported"
#error "platform unsupported"
 ^
/usr/local/include/handy/poller.h:73:2: error: "platform not supported"
#error "platform not supported"
 ^
2 errors generated.

**Comment by vincent-coding** [comment]
要自己定义 OS_MACOSX 吗？

**Comment by yedf** [comment]
https://github.com/yedf/handy/issues/6
