### ISSUE TITLE
求助：代码片段疑问

### ISSUE THREAD

**Issue by adomy** [yedf/handy#31]
handy/threads.h文件中：

`std::vector<std::thread> threads_;`

handy/threads.cc文件中：

```
ThreadPool::ThreadPool(int threads, int maxWaiting, bool start): 
tasks_(maxWaiting), threads_(threads)
{
    if (start) {
        this->start();
    }
}
```

这里初始化列表对于threads_的初始化是否存在问题？？求解答。

**Comment by mingyuejingque** [comment]
threads_(threads)；   
这里表示 threads_  这个vector 的初始容量是 threads 个。
类似的例子：  char *p = new char[ threads ];   跟初始大小有关的意思了。
