### ISSUE TITLE
有关handy的logger对于异步考虑的问题

### ISSUE THREAD

**Issue by yangbodong22011** [yedf/handy#34]
感谢作者贡献的handy。
handy的日志是采用write(O_APPEND)的方式，非常简洁并且这种方式又可以保证原子，但是如题，handy的日志只是在本线程写，那么当这个线程需要写大量的日志时，即大量调用write(2)的时候，会不会对它的处理来说是一种负担？所以作者有将日志做成异步的考虑吗？

**Comment by yedf** [comment]
这个问题在设计之初就有考虑过，我有专门测试过打日志的性能，每秒钟几十万次的调用性能吧。从大家大多数的业务场景来考虑的话，这个优化方案并不着急
