### ISSUE TITLE
请问handy库为什么要用管道来唤醒I/O线程？

### ISSUE THREAD

**Issue by onlyet** [yedf/handy#35]
正在学习您的handy库，不明白为什么要用管道来唤醒I/O线程，任务队列不是有条件信号吗，条件等待的时候线程挂起就不占用资源了吧？所以我就是没明白用管道唤醒然后去条件等待的目的

**Comment by yedf** [comment]
IO线程如果挂起，那么就不处理IO了，就会导致全部连接都没有响应。
使用管道，会统一走入epoll，然后非阻塞式的取获取任务，这样能够保证IO线程值会在所有IO操作都处理完的情况下才挂起，并且有任何IO到来的时候，会被唤起
