### ISSUE TITLE
在一个应用程序里面同时启动一个HttpServer和一个TcpServer，不同端口；是否可行？

### ISSUE THREAD

**Issue by hug2008** [yedf/handy#51]
在一个应用程序里面同时启动一个HttpServer和一个TcpServer，不同端口；
是否可行？
如可以，如何实现？

**Comment by jovan-wong** [comment]
Certainly it's.
There are 2 ways to approach it:
1. You could add the `Tcp server` and `Http server` into one event loop if you want to start 2 servers.
2. You could start 2 servers in different event loop also. but an event loop would block the current thread, so you  could start 2 event loops in different threads.
