### ISSUE TITLE
关于测试程序一些问题

### ISSUE THREAD

**Issue by buptbill220** [yedf/handy#57]
https://www.oschina.net/p/c11-handy
关于测试性能对比那里，nginx配置
worker_processes=1
location /hello {
echo "hello world!"
}
这里为worker数量为啥配置成1呢，t420 应该是双核吧。master作为io进程基本消耗不了多少cpu，所以cpu打不满。能测试下worker_processes=2情况下的数据么，以及各个测试系统资源情况

**Comment by jimmy-kuo** [comment]
作者打算如何利用服务器的SMP的CPU架构？

**Comment by yedf2** [comment]
对比测试中，大家都是单线程
