### ISSUE TITLE
OSX10.11 编译ExampleDemo出错

### ISSUE THREAD

**Issue by dongjiahong** [yedf/handy#6]
```
#include <handy/handy.h>

using namespace std;
using namespace handy;

int main(int argc, const char* argv[]) {
    EventBase base; //事件分发器
    //注册Ctrl+C的信号处理器 -- 退出事件分发循环
    Signal::signal(SIGINT, [&]{ base.exit();});

    TcpServer echo(&base);  //创建服务器
    int r = echo.bind("", 99); //绑定端口
    exitif(r, "bind failed %d %s", errno,strerror(errno));
    echo.onConnRead([](const TcpConnPtr& con) {
        con->send(con->getInput()); //echo 读取的数据
    });
    base.loop();    //进入事件分发循环
}
```

`clang++ -std=c++11 demo.cpp -omain`

In file included from echo.cpp:1:
In file included from /usr/local/include/handy/handy.h:4:
In file included from /usr/local/include/handy/http.h:4:
In file included from /usr/local/include/handy/conn.h:2:
In file included from /usr/local/include/handy/event_base.h:3:
/usr/local/include/handy/poller.h:14:2: error: "platform unsupported"
#error "platform unsupported"
 ^
/usr/local/include/handy/poller.h:73:2: error: "platform not supported"
#error "platform not supported"

**Comment by yedf** [comment]
已解决

在这个fix之前，你可以在examples目录下编写你的代码，使用make来生成最终程序
这个fix把头文件中对OS_MACX的依赖放到了cc文件中。因此编译例子程序时，不再需要config.mk中的环境变量
