### ISSUE TITLE
请问 TcpServer 有多线程的支持吗？

### ISSUE THREAD

**Issue by ranqiyu** [yedf/handy#64]
看见了 HSHA ，这个就是 tcp server 的多线程封装吗？
请问为什么称为半同步半异步服务器？

**Comment by yedf2** [comment]
IO操作是异步的，多连接共享一个县城。业务逻辑处理是同步的，一个请求处理需要占用线程池中的一个线程

**Comment by ranqiyu** [comment]
> IO操作是异步的，多连接共享一个县城。业务逻辑处理是同步的，一个请求处理需要占用线程池中的一个线程

那是不是可以将业务逻辑这一块分发到工作线程池中去呢？那就变成HAHA了。？

**Comment by yedf2** [comment]
将业务逻辑这一块分发到工作线程池中去呢，我们称他为HSHA呢
