### ISSUE TITLE
编译 代码示例--echo-server后出错

### ISSUE THREAD

**Issue by jievince** [yedf/handy#67]
/tmp/ccrj5xT1.o: In function `main::{lambda()#1}::operator()() const':
me.cpp:(.text+0xbd): undefined reference to `handy::EventBase::exit()'
/tmp/ccrj5xT1.o: In function `main::{lambda(std::shared_ptr<handy::TcpConn> const&)#2}::operator()(std::shared_ptr<handy::TcpConn> const&) const':
me.cpp:(.text+0xff): undefined reference to `handy::TcpConn::send(handy::Buffer&)'
/tmp/ccrj5xT1.o: In function `main':
me.cpp:(.text+0x136): undefined reference to `handy::EventBase::EventBase(int)'
me.cpp:(.text+0x166): undefined reference to `handy::Signal::signal(int, std::function<void ()> const&)'
me.cpp:(.text+0x1bd): undefined reference to `handy::TcpServer::startServer(handy::EventBases*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned short, bool)'
me.cpp:(.text+0x1f2): undefined reference to `handy::Logger::getLogger()'
me.cpp:(.text+0x223): undefined reference to `handy::Logger::getLogger()'
me.cpp:(.text+0x24f): undefined reference to `handy::Logger::logv(int, char const*, int, char const*, char const*, ...)'
me.cpp:(.text+0x2ab): undefined reference to `handy::EventBase::loop()'
me.cpp:(.text+0x2c9): undefined reference to `handy::EventBase::~EventBase()'
me.cpp:(.text+0x33d): undefined reference to `handy::EventBase::~EventBase()'
collect2: error: ld returned 1 exit status

**Comment by jovany-wang** [comment]
能给出你的环境和配置吗？
