### ISSUE TITLE
net.h--addSize 存在内存越界访问的情况

### ISSUE THREAD

**Issue by liaodong** [yedf/handy#68]
addSize不做越界检查，可能会存在buffer空间不够的情况越界访问吧。

如果空间超过exp_, 应该做相应的处理。

**Comment by yedf2** [comment]
一般情况下使用：
buf.append(data)

有时为了避免数据拷贝，会采用下面这种用法
char * p = buf.makeRoom(2048)
// copy n bytes data
buf.addSize(n)

只有在很关注性能时，才会使用addSize时，因此实现时，不应做过多的检查与操作，避免影响性能

**Comment by liaodong** [comment]
我在用httpserver，发现同一个TCP连接中，如果客户端发送多条数据，会造成 httpserver的buffer的越界。猜测可能是addSize造成的。

**Comment by yedf2** [comment]
您好，目前这个httpserver只是具备的最简单的功能，对于您这边的发送多条数据这类高级一些的用法，我们还不支持

**Comment by jievince** [comment]
@yedf2 你好, 请问基于handy库和RFC2616(http协议)实现一个完整的http服务器在技术上可行的吗?

**Comment by yedf2** [comment]
您好，现有的nginx能够满足绝大部分需求，因此我们没有打算基于handy再实现一个
