### ISSUE TITLE
Buffer对象是线程安全的吗？

### ISSUE THREAD

**Issue by liaodong** [yedf/handy#69]
Buffer对象是线程安全的吗？

**Comment by yedf2** [comment]
不是线程安全的，对于使用的类库，除非特别声明是线程安全的，否则都是非线程安全的。例如stl都是非线程安全的

**Comment by gdlxSong** [comment]
线程安全势必降低效率，所以线程安全留给使用者把握就好了吧，不过倒是可以做一个copy on write的Buffer
