### ISSUE TITLE
看性能测试报告好像和MUDUO有一些差距啊

### ISSUE THREAD

**Issue by bigbao9494** [yedf/handy#71]
MUDUO作者的测试是高出LIBEVENT有15~20%，请问这为什么？
@yedf2

**Comment by yedf2** [comment]
handy追求代码简洁易用，并不一味追求性能。
当今的nginx性能已经非常高，一台服务器，通常连接层面就能够处理百万用户并发，通常都不是瓶颈。
因此更多是追求更易用的代码，更好的稳定性
