### ISSUE TITLE
使用echo来ping_pong测试，5万个连接

### ISSUE THREAD

**Issue by bigbao9494** [yedf/handy#72]
使用echo来ping_pong测试，5万个连接，没有任何信息程序就退出了，没有打印异常信息
这是为什么呢？？
系统参数都是修改过了的。
ping_pong：连接建立后以8K数据向服务器发数据然后再收，收到服务器数据后再发，中间不停顿这样循环，来测试处理能力

**Comment by yedf2** [comment]
您好，您可以开启core dump，看看具体发生了什么错误
具体您可以搜索一下
