### ISSUE TITLE
EdgeTrigger下当Socket同时变为可读可写时不会丢失对handleWrite的处理吗？

### ISSUE THREAD

**Issue by demonatic** [yedf/handy#74]
>  if (events & (EPOLLIN | EPOLLERR)) {
>             if (fd == lfd) {
>                 handleAccept(efd, fd);
>             } else {
>                 handleRead(efd, fd);
>             }
>         } else if (events & EPOLLOUT) {
>             if (output_log)
>                 printf("handling epollout\n");
>             handleWrite(efd, fd);

当Socket读和写都返回了EAGAIN，epoll_wait返回时EPOLLIN和EPOLLOUT可能同时有效，由于使用if判断EPOLLIN+else if判断EPOLLOUT，所以只有handleRead分支被执行了，handleWrite分支未得到执行。由于是边沿触发，socket可写事件被触发一次之后不会再被触发。

**Comment by yedf2** [comment]
您好，如果要真正解决这个问题，需要大量的代码进行精细处理（因为各个处理都有可能出错并关闭连接）。
例子为了保持简洁性，因此没有很好的处理这种极端情况。
我在代码中添加了注释，提醒用户这个问题。
谢谢您的建议
