### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [yedf/handy#8]
[An extra null pointer check is not needed](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8 "Do I need to check for NULL before delete p?") in [the function "TcpConn::attach"](https://github.com/yedf/handy/blob/332a7974e7b1bc53562703599f4f72df53061963/handy/conn.cc#L15 "Update candidate: TcpConn::attach()").

**Comment by yedf** [comment]
fixed.
thank you for your comments.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/yedf/handy/commit/0ac28ff02b4bf994d2dd26f9a04cbc9229c56c51 "Deletion of an unnecessary check").
