### ISSUE TITLE
在handy中编写自己的业务逻辑

### ISSUE THREAD

**Issue by momentliu** [yedf/handy#81]
hi，你好，想咨询下handy支持rd写自己的业务逻辑吗？比如handy只负责网络收发请求，但请求的解析，处理，封装由rd开发的代码逻辑来完成？

**Comment by jovany-wang** [comment]
支持的。 具体的例子可以参考自定义一个pb的实例，你可以把你这里的pb当作是你自己要实现的部分。 https://github.com/yedf/handy/tree/master/protobuf

**Comment by momentliu** [comment]
好的，多谢。
