### ISSUE TITLE
Logger 的logv 多线程并发访问时可能会导致write失败

### ISSUE THREAD

**Issue by in-han** [yedf/handy#95]
首先，阅读该框架很受益，感谢 !!!

提一个问题:
Logger日志切割的逻辑中，一个线程执行dup2时，另一个线程写原fd_时，可能会遇到文件句柄已关闭，导致写失败的情况。
日志切割代码如下:
`void Logger::maybeRotate() {
    time_t now = time(NULL);
    if (filename_.empty() || (now - timezone) / rotateInterval_ == (lastRotate_ - timezone) / rotateInterval_) {
        return;
    }
    lastRotate_ = now;
    long old = realRotate_.exchange(now);
    //如果realRotate的值是新的，那么返回，否则，获得了旧值，进行rotate
    if ((old - timezone) / rotateInterval_ == (lastRotate_ - timezone) / rotateInterval_) {
        return;
    }
    struct tm ntm;
    localtime_r(&now, &ntm);
    char newname[4096];
    snprintf(newname, sizeof(newname), "%s.%d%02d%02d%02d%02d", filename_.c_str(), ntm.tm_year + 1900, ntm.tm_mon + 1, ntm.tm_mday, ntm.tm_hour, ntm.tm_min);
    const char *oldname = filename_.c_str();
    int err = rename(oldname, newname);
    if (err != 0) {
        fprintf(stderr, "rename logfile %s -> %s failed msg: %s\n", oldname, newname, strerror(errno));
        return;
    }
    int fd = open(filename_.c_str(), O_APPEND | O_CREAT | O_WRONLY | O_CLOEXEC, DEFFILEMODE);
    if (fd < 0) {
        fprintf(stderr, "open log file %s failed. msg: %s ignored\n", newname, strerror(errno));
        return;
    }
    dup2(fd, fd_);
    close(fd);
}`

构造例子:
`
#include <iostream>
#include<thread>
#include<sys/types.h>
#include<sys/stat.h>
#include<fcntl.h> 
#include <time.h>
#include <unistd.h>
#include <sstream>

using namespace std;

string old_name = "data/tmp.txt";

int main(){
    int fd = open(old_name.c_str(),O_WRONLY|O_APPEND|O_CREAT|O_CLOEXEC, DEFFILEMODE);

    thread th1([=](){
       cout << "hello" << endl;
       while(true){
           ssize_t size=write(fd, "A\r\n", 3);
           if(size < 0 ){
               cout << "write return error:" << size << ", " << errno << "," << strerror(errno) << endl;
               exit(0);
           }
       }
    });
    thread th2([=](){
       int i = 0; 
       while(true){
            i ++;
            stringstream new_name;
            new_name << old_name << "." << i;

            int err = rename(old_name.c_str(), new_name.str().c_str());
            if( err != 0 ){
                cout << "rename fail:" << err << endl; 
                continue;
            }

            int tmp_fd = open(old_name.c_str(), O_APPEND | O_CREAT | O_WRONLY | O_CLOEXEC, DEFFILEMODE);
            if (tmp_fd < 0) {
                cout << "open new file fail:" << tmp_fd << endl; 
                continue;
            }

            dup2(tmp_fd, fd);
            close(tmp_fd);
        }    
       
   });

   th1.join();
   th2.join();
}`

运行结果:
![image](https://user-images.githubusercontent.com/4653075/124228540-ec122700-db3e-11eb-9228-a8fdf504b8fb.png)

**Comment by yedf2** [comment]
已修复
